/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        /* Stitch / Material 3 design tokens */
        "error": "#ffb4ab",
        "surface-bright": "#3a3939",
        "secondary-fixed-dim": "#e9c400",
        "primary-m3": "#ffe2ab",
        "inverse-on-surface": "#313030",
        "on-surface-variant": "#d4c5ab",
        "surface-tint": "#fbbc00",
        "primary-container": "#ffbf00",
        "on-tertiary-container": "#005d6d",
        "on-primary-container": "#6d5000",
        "on-primary-fixed": "#261a00",
        "surface-variant": "#353534",
        "on-error": "#690005",
        "tertiary-fixed": "#aaedff",
        "on-secondary-fixed-variant": "#544600",
        "on-secondary-container": "#725f00",
        "on-primary": "#402d00",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#ffe16d",
        "surface-container": "#201f1f",
        "secondary-m3": "#fff9ef",
        "surface-container-high": "#2a2a2a",
        "surface-m3": "#131313",
        "outline-m3": "#9c8f78",
        "on-tertiary-fixed-variant": "#004e5c",
        "primary-fixed-dim": "#fbbc00",
        "tertiary-m3": "#b4efff",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#001f26",
        "error-container": "#93000a",
        "tertiary-container": "#04dcff",
        "secondary-container": "#ffdb3c",
        "primary-fixed": "#ffdfa0",
        "on-primary-fixed-variant": "#5c4300",
        "inverse-primary": "#795900",
        "on-tertiary": "#003640",
        "outline-variant": "#504532",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#00d9fc",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface-container-highest": "#353534",
        "on-background": "#e5e2e1",
        "on-secondary": "#3a3000",
        "surface-dim": "#131313",
        "on-secondary-fixed": "#221b00",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
